### ISSUE TITLE
Is it possible to open porcupine in one frame of my on app tkinter?

### ISSUE THREAD

**Issue by paulokanda** [Akuli/porcupine#1033]
Firstly thank you very much  for your time and sharing with the community, porcupine,  this much more than "decent" editor.  I don't know if this is the correct place to ask my question but I would like to open porcupine in a tkinter frame of my own, create (manually) some restructured text, and export it to html  and pdf. Is that possible. Thanks in advance for any suggestion.

https://stackoverflow.com/questions/70906761/is-that-possible-to-insert-porcupien-text-editor-in-a-tkinter-window-of-my-app?noredirect=1#comment125351719_70906761

Kanda

**Comment by Akuli** [comment]
Indeed, this is the right place to ask about anything related to Porcupine :)

Porcupine wasn't designed with this in mind. You can see it in `_state.py`, where it creates a global root window (`tkinter.Tk`), and exposes it in `get_main_window()`. The rest of porcupine calls `get_main_window()` in many places.

If we get rid of the concept of a main window, and replace it with a frame, you could then create your own Porcupine instance in a frame. But only one instance at a time: because Porcupine uses global variables in `_state.py` and a few other files, two simultaneous Porcupine frames would conflict. It would be more work to refactor Porcupine so that this works.

However, Porcupine is much easier to extend if you're fine with using its root window. This is what Porcupine plugins do. Plugins can customize pretty much everything, and you can get a good idea of how powerful they are by running Porcupine with `--no-plugins`. Exporting RST to HTML or PDF seems like something suitable for a plugin.

**Comment by Akuli** [comment]
Let me know if you're still interested in this, and we can discuss more.
