### ISSUE TITLE
Suggestion: Remove usage of .update()

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1127]
You may find [this](https://tkdocs.com/tutorial/eventloop.html#:~:text=When%20you%20use,haven%27t%20been%20warned...) from tkdocs quite interesting on why not to use `.update()`. Regarding the implications that this makes I think it would be good to change from `.update()` to `.update_idletasks()`

**Comment by Akuli** [comment]
The doc you linked is about using `.update()` in a loop, between steps of a long-running operation. Porcupine doesn't use `.update()` in that way: all uses of `.update()` (outside tests) are one-time things that are done soon after the first and only `.update()` is done.

I'm going to close this for now. If you experience practical problems that you suspect might be because of `.update()`, just let me know. If you hate `.update()` and want it removed, you can:
- Go through the 4 usages of `.update()` in Porcupine, figure out why each one is needed, and whether `.update_idletasks()` could replace it. Two of the usages even have a comment on them that might help.
- Actually learn how event loops work and actually understand the docs you linked.

I'm sorry if this came off as rude, but I'm not the kind of person who blindly believes "never use X". I want to understand what's actually going on, and **when** and **why** X is bad. The tkdocs you linked it do explain it, and as I said, Porcupine doesn't do the bad thing they are describing.

**Comment by Moosems** [comment]
Thanks for the explanation. Duly noted

**Comment by rdbende** [comment]
I find that in general, the problem with `.update()` is more the fact that people don't understand what it actually does, rather than what it can actually do. At least in Tkinter.

Since `update` is a method of `tkinter.Misc`, every widget inherits it, and therefore it would seem kind of logical that it is used to update or redraw the widget, however in fact it has nothing to do with the widget but rather with the main loop in general. In Tcl this is much less ambiguous, as `update` is a built-in command in the language.

There are two common uses I've seen and none of them are right.

```python
b = tkinter.Button()

b.config(bg="red")
b.update()  # Pointless and misleading
```

```python
def process():
    for _ in range(100):
        time.sleep(0.1)
        p.step()
        p.update()  # p.after()? 🤔

p = ttk.Progressbar(root)
p.pack()

process()
```

In most cases `update`-ing is pointless, or the code could be refactored to not use `.update()` at all, and this also shows that unfortunately people don't know what it's actually doing. But this isn't the case with @Akuli, as he's usually quite aware of what he's using and when.
