### ISSUE TITLE
Stupid edge case: 100,000 lines makes linenumber go off of the edge

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1156]
We should have the linebar either resize itself to fit the linenumber or have it change the font size of the linenumbers such that it fits the canvas. I know from experience that when there is a way, someone will always somehow meet an edge case no matter how ridiculous. I could do this by measuring the numbers length and then testing font sizes to see when it fits or just resize the linebar to that measured area

**Comment by rdbende** [comment]
I think, if someone has 100000 lines of code in a songle file, they deserves not to see all the linenumbers.

**Comment by Moosems** [comment]
XD same but I foresee it more likely being some stupidly long logging file for work

**Comment by Akuli** [comment]
I created a test file with 100000 lines of a realistic length:

```
akuli@akuli-desktop:~/porcu$ for i in {1..100000}; do echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx >> log.txt; done

akuli@akuli-desktop:~/porcu$ wc -l log.txt
100000 log.txt

akuli@akuli-desktop:~/porcu$ ls -lh log.txt
-rw-r--r-- 1 akuli akuli 4,1M 17. 8. 20:39 log.txt
```

Because the test file is bigger than 1MB, Porcupine shows a warning when you try to open it.

![w](https://user-images.githubusercontent.com/18505570/185206214-91a378f3-efab-47b0-8685-20165ff39c0d.png)

I happened to use 42 characters (41 `x` + 1 newline) per line in my test file, which made its size 4.2MB (although M actually meaning MiB produces a slightly different result in the `ls` output). Porcupine's warning triggers at 1MB, which corresponds to 10 characters per line. I think any kind of practical file is longer than that on average.

I can fix this if it actually comes up, but until then, there's already a warning that Porcupine might not work correctly.
