### ISSUE TITLE
UTF-8 BOM 

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1239]
lol

Porcupine doesn't detect a UTF-8 BOM at the start  of a file. Instead it reads it as a normal character which happens to be `U+FEFF ZERO WIDTH NO-BREAK SPACE`. Also, it is impossible to delete this character by pressing backspace (but the delete key works).

To reproduce:

```
>>> open('/tmp/asd.txt','w',encoding='utf-8-sig').write('moi')
```

**Comment by taahol** [comment]
One part of the problem is that a request for dedention is sent by Tcl: https://github.com/Akuli/porcupine/blob/929e61249e57e43122d32a039525ace2a5788259/porcupine/default_keybindings.tcl#L149-L150 and handled by Python: https://github.com/Akuli/porcupine/blob/929e61249e57e43122d32a039525ace2a5788259/porcupine/textutils.py#L748-L751 while the case is that they cannot agree on whether the UTF-8 BOM is a space:
```python
>>> tkinter.Tcl().eval(f"string is space {codecs.BOM_UTF8.decode('utf-8')}")
'1'
>>> codecs.BOM_UTF8.decode("utf-8").isspace()
False
```
