### ISSUE TITLE
Make `<<Cut>>` actually cut normally

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1288]
In most editors and most websites, cut will delete either the selected text or the line currently containing the insert. However, default `tkinter`'s cut runs only when there is selected text. While I have tried overriding the `<<Cut>>` bind using `bind_class()` and `bind()` I have been unable to make it work in `porcupine` or even a regular Text widget. I would like a better cut method as I do personally use it so I'm interested to hear your thoughts.

**Comment by Moosems** [comment]
I figured out a way to do it, sadly it requires `return "break"`, my least favorite thing in `tkinter`. Hopefully I will find another workaround that doesn't require something so crude.

**Comment by Akuli** [comment]
I would be surprised if something is cut when I have nothing selected, so it shouldn't be the default behavior :)

That said, you can put this to `keybindings.tcl` (Settings --> Config Files --> Edit keybindings.tcl) to cut the current line when nothing is selected:

```tcl
set old_cut_binding [bind Text <<Cut>>]
bind Text <<Cut>> {
    if {[%W tag ranges sel] == ""} {
        %W tag add sel "insert linestart" "insert linestart + 1 line"
    }
}
bind Text <<Cut>> +$old_cut_binding
```

This rebinds `<<Cut>>` (similar to `bind_class()`), but adds the new code to the *beginning* rather than the end. The new code selects the current line if nothing is selected, and then lets the original cutting code do its thing.

**Comment by rdbende** [comment]
> `return "break"`, my least favorite thing in tkinter.

??

**Comment by Moosems** [comment]
> > `return "break"`, my least favorite thing in tkinter.
> 
> ??

It negates any other binds someone might make

**Comment by rdbende** [comment]
Yeah, that's the point of it.

**Comment by Moosems** [comment]
I know, but I don't like making other binds possibly negated.
