### ISSUE TITLE
Use pyeditorconfig :D

### ISSUE THREAD

**Issue by Moosems** [Akuli/porcupine#1290]
I created [pyeditorconfig](https://github.com/Moosems/pyeditorconfig) based on (copy/pasted) your code as you recommended.

**Comment by Moosems** [comment]
@Akuli I updated it to be better :D.

**Comment by Akuli** [comment]
To be honest, I don't like the idea of making Porcupine depend on more libraries, just like how you didn't want to include all of PIL in your editor a while ago. If you ask "how does editorconfig work in Porcupine?", you can read the editorconfig plugin. Because it only uses the standard library, that's all you need to read. I really like that: Porcupine is truly self-contained in many ways. But I also understand that you want me to use your libraries :)

That said, there is one case where I wanted to split away some of the logic into a separate library. Porcupine's langserver plugin uses `sansio-lsp-client`, which handles many details, like formatting messages as jsonrpc and parsing the responses into nice data structures. Even with that library, the langserver plugin is 783 lines, so it is really needed. I just don't think editorconfig is like that at all.

**Comment by Moosems** [comment]
Didn't you say that if I made it into a package that you would use the package 😆? I get the self-contained sentiment though, I share that in many ways.
