### ISSUE TITLE
Documentation is a mess

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#1308]
Porcupine currently has many kinds of documentation:
- akuli.github.io/porcupine, aka Plugin API docs. Some pages are pretty good, e.g. https://akuli.github.io/porcupine/settings.html and https://akuli.github.io/porcupine/plugin-intro.html. A problem is that contributors are usually not familiar with how sphinx works, so these don't get updated much. Also, much of these are autogenerated from docstrings, so pretty pointless if you're going to read the source code anyway.
- Porcupine Wiki. Outdated. I'm pretty convinced nobody reads this.
- CONTRIBUTING.md. Good stuff.
- Large comments in config files (see default_filetypes.toml)

There is currently no documentation about:
- Design philosophy: small core with powerful plugins. What are the advantages and disadvantages of this design and how far we take it.
- File structure: what file should you look at if you want to fix something?
- What each thing in the UI does. I'm pretty satisfied with the picture in mantaray's docs: https://github.com/Akuli/mantaray/blob/3241303/README.md#how-mantaray-works

This is overall a mess. I would suggest:
- Move the good parts of existing documentation to markdown files. Very easy to view and edit for everyone.
- Document more stuff into markdown files
- Keep existing docstrings
- Get rid of akuli.github.io/porcupine

Thoughts? (from everyone, including experienced and new Porcupine developers and)

**Comment by benjamin-kirkbride** [comment]
I would like to see more patterns documented, it's pretty daunting trying to get started.

For instance, I'm looking at the `dedent` method of the `MainText` widget.

There is a lot to figure out here. If there was a "cookbook" of common patterns that would make getting started a lot less daunting.

**Comment by benjamin-kirkbride** [comment]
Example of the sort of thing I found difficult to figure out: https://www.phind.com/search?cache=7a4294b3-9ca4-49cd-a21e-e37350f316d5

**Comment by rdbende** [comment]
> I would like to see more patterns documented, it's pretty daunting trying to get started.

I second that. When I start working on a new plugin, I always just copy an existing one, and delete what I don't need, because I can't remember how to implement all the fun stuff, like `on_new_filetab`, etc.

I rarely look at the docstrings, but rather use the web docs. It's easier for me to find what I'm looking for, but then go usually back to the source code, to read, what it actually does :D

Also:
```
$ git grep "# TODO: document this" | wc -l
20
```

**Comment by rdbende** [comment]
Actually I think we should keep the website for new and non-developer users, but what's currently on the wiki (if no one reads them, imo it's because Github wikis are inconvenient and many people aren't even aware of them) and the "What each thing in the UI does" should go to https://akuli.github.io/porcupine, and the rest into markdown files.
Then we should also put a link to the repo sidebar, so it's easier to discover it.

**Comment by Akuli** [comment]
So what would distinguish "this belongs to akuli.github.io/porcupine" and "this belongs to a markdown file", and why would you distinguish them in exactly that way? What advantages and disadvantages of each documentation place do you take in account?

To me these are hard questions, and if the answers aren't simple and clear, splitting it to two places could be more confusing than helpful. That's why I wanted to put it all into one place, even if that one place isn't as good for some things as the other place. And if it's all in one place, it should probably be markdown because people are familiar with it.

**Comment by rdbende** [comment]
I would categorize them as "docs on how to use Porcupine" (user guide) versus "docs on how to develop Porcupine" (dev guide).

The first contains information about how to install and use Porcupine as a text editor (e.g. user interface, keyboard shortcuts, and stuff that's currently on the wiki), while the second is about API docs, design philosophy, file structure and the like, as well as some kind of tutorial on creating a new plugin or adding new tree sitter languages.

Because if I were a user seeking for a good text editor, I would not waste my time browsing the source code and markdown files, but instead click on the first link that catches my eye on the Github page. Whereas, if my goal was to write a new plugin or fix a bug, I would consult the API documentation, which is already in my local repository.

**Comment by Akuli** [comment]
The more I think about this, the more I want to just make a folder for documentation and shove markdown files there, without any kind of automated build or anything else fancy. Basically, documentation should be as painless and simple as possible. Otherwise it is never written or it isn't maintained properly, and we currently have a mix of both.

I like separating user docs and dev docs, but I want it to be just markdown files in folders. Maybe `user-doc` and `dev-doc` folders?

It seems like the only thing we don't agree about is sphinx-generated documentation, aka akuli.github.io/porcupine. I want to delete sphinx. It adds complexity and burden to docs for little benefit. For example, the sphinx build is currently failing with some error, so if sphinx documentation was added now, nobody would see it other than by looking at docstrings.

IMO a better alternative to sphinx would be just reading the docstrings. They could be written to be human-readable rather than computer-parseable, which would make them easier to write and maintain. Also, when you use jump-to-definition, you see the docstring, not a sphinx-generated result.

**Comment by Akuli** [comment]
Porcupine's documentation is no longer a mess. It is now clearly split into `dev-doc` and `user-doc` folders.
