### ISSUE TITLE
Should functions that return `break` be annotated `Literal["break"]`?

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1309]
I know nothing, so disregard if this is dumb

**Comment by Akuli** [comment]
Good question :)

When I started type annotating Porcupine, type annotated tkinter wasn't really a thing. I ended up rewriting the tkinter stubs in typeshed. Typeshed is the place where type checkers look to figure out what the standard library contains, what types your callback function should return, and so on. So basically, I made tkinter work with type annotations much better than before.

Initially I typed `bind()` methods as needing a callback that returns `Optional[Literal["break"]]` (or with newer syntax, `Literal["break"] | None`), so that you would need to spell the return type as something like `Literal["break"]`, or `Literal["break"] | None` if you don't always break. My idea was that `return "braek"` or similar would be a type checking error.

But that caused problems when I put `after_idle()` inside a bind, because `after_idle()` returns a string that is not `"break"`: https://github.com/python/typeshed/issues/5010

To fix that, I changed typeshed to accept anything for the return type. Porcupine now uses `str` because it's simpler than `Literal["break"]`. But because `Literal["break"]` is also a valid `str`, it would work too.
