### ISSUE TITLE
Update README with what makes Porcupine special

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1325]
> I agree with everything you said about README. Feel free to make a PR :)

_Originally posted  in https://github.com/Akuli/porcupine/issues/1324#issuecomment-1619091883_
      
---

The value positioning of this project should be tweaked slightly in the README. The list of features is not a bad thing to have, but obviously going head to head on features against basically any other Editor/IDE that anyone would have heard of, Porcupine does not hold a candle.

IMO the thing that is exciting about Porcupine is that it is very easy to extend using Python: I went from 0 to having a Markdown Plugin written in like 8 hours? I don't think there is any other Python IDE out there that comes remotely close. Even PyCharm uses not-Python for it's extensions (Java). Beyond that, everything about Porcupine is extensible and changeable, fairly easily. VSCode obviously has way more extensions, but there are a ton of things you CAN'T change about it, because they don't expose the API you would need. This makes VSCode a poor choice for a lot of applications.

I think we should hit the points above early, and hard in the docs. Make it clear that Porcupine is THE editor for people who want to hack on their editor in Python, first and foremost. Then discuss how it is a pretty good editor broadly.

**Comment by benjamin-kirkbride** [comment]
After more thought, I think we should also position Porcupine as a sort of spiritual successor to IDLE: a pure Python editor that is beginner friendly that was designed for the 2020's: you have auto formatting and language servers and git support built in, etc.

**Comment by Moosems** [comment]
It takes a lot of new looks on old topics and provides a new fresh experience unlike most other editors and incredibly slow on Macs 🤣.

**Comment by rdbende** [comment]
Once I tried it in a VM. It wasn't slow.

**Comment by Moosems** [comment]
Huh, maybe I just have a weird one.

**Comment by benjamin-kirkbride** [comment]
Interesting discussion on HN here: https://news.ycombinator.com/item?id=36754406

Before deciding do start helping with Porcupine, Neovim was my #2 choice. I knew I wanted something that was configurable and more on the editor side than the IDE side. The thing that ultimately made the decision for me was how fragmented the community for vim is, being able to use a mouse as a 1st class input device, and being able to use Python for plugins, and being able to share my work with people who aren't super geeks (can't really make something that my parents could use if I devoted my time to vim).

**Comment by rdbende** [comment]
Speaking of which, I started with Geany on a Raspi, then used Thonny, and now Porcupine for over three years. Haven't thought about switching to anything else since.

**Comment by Akuli** [comment]
For me, it was rougly IDLE -> Geany -> emacs -> nano -> porcupine. And yes, the initial version of Porcupine was written in nano, until it was good enough so I could use it to write itself :)

I can't really use the vim family of editors for real work, because my fingers are too used to "normal" editors. I haven't really tried though. I know enough vim to use it for a few minutes in a pinch, like editing a commit message after installing Git for Windows, if I forgot to select nano when installing.

At work I currently have a not-so-ideal setup with Porcupine and a large C project, pretty similar to the rust_analyzer experience on the HN thread (throw something in PATH, edit config file, hope for the best). I know things would "just work" with vscode, as everyone else on the team uses it. Hopefully things will get to that point with Porcupine and C eventually :)
