### ISSUE TITLE
Enhancement: Switch to CustomTkinter

### ISSUE THREAD

**Issue by dishb** [Akuli/porcupine#1393]
Have you thought of using [CustomTkinter](https://github.com/TomSchimansky/CustomTkinter)? It would make the UI look much better right off the bat. It is open-source with great [documentation](https://customtkinter.tomschimansky.com). Themes can easily be added with `.json` files. Many people have created applications to create CustomTkinter themes.

This would be a massive task considering the codebase and how far into development the project is. However, most widgets can easily be converted by suffixing `customtkinter.` and changing the widget to `CTk` + the widget's name.

CustomTkinter is built on top of native Tkinter widgets which means they can interact together without many problems.

Some Tkinter widgets don't have CustomTkinter counterparts such as the `Treeview()` widget. Furthermore, `tkinter.ttk` widgets do not have any CustomTkinter equivalents.

Making this switch would lead to a better UI but also mean you'd have to drop `tkinter.ttk`.

**Comment by Moosems** [comment]
He once tried something similar with his own project `Teek` but because Porcupine is so large these modules like CustomTkinter cause a lot more bloat and slow down the program significantly. I love the idea but sadly I don't see it happening.

**Comment by Moosems** [comment]
Being restricted to certain widgets and barred from widgets like the Treeview would also cause many problems I don't think Akuli would care enough to spend a load of time on.

**Comment by rdbende** [comment]
I do get the hype around Customtkinter, it's indeed awesome that you can customize the UI however you want, but here are my counter-arguments:

1. Customtkinter is unbearably slow/laggy for me
2. Customtkinter is ugly IMO. Because the canvas doesn't have antialiasing, and this flat design with the disproportionate borderwidths and other elements looks kinda... weird.
3. Currently Porcupine uses a [ttk theme created by me](https://github.com/rdbende/Sun-Valley-ttk-theme), and I don't want to switch to something else XDD. (btw I have great new about sv-ttk, tho I think it's not public yet :))

[Here](https://github.com/rdbende/Sun-Valley-ttk-theme/issues/92#issuecomment-1634560061) can you read my general opinion on Customtkinter.

I don't know what others think about this though. Why don't we #RIIR anyway? :P

**Comment by Moosems** [comment]
I suspect Akuli will have similar opinions.

**Comment by Akuli** [comment]
Indeed, I agree with everything that is said here :)

**Comment by Akuli** [comment]
> #RIIR

A bit off-topic for this issue, but this isn't actually the first time someone suggests rewriting porcupine in a faster language. (I know this time it was a joke, but still.)

I have once [rewritten a large-ish Python project in rust](https://github.com/Akuli/catris/pull/226). I don't want to go through the same process with Porcupine:
- Porcupine is in no way unbearably slow as is (unless you are Moosems).
- Most performance bottlenecks in Porcupine are easy enough to solve within Python.
- A rewritten Porcupine wouldn't feel like Porcupine. To me, Porcupine is the weird tkinter project that is surprisingly good/usable considering it's just tkinter.

**Comment by Moosems** [comment]
Yeah I wouldn't rewrite in a different language but it really is slow 🤣. It takes me 10+ seconds to open Porcupine and 5+ to open or close a tab.

**Comment by rdbende** [comment]
> I have once [rewritten a large-ish Python project in rust](https://github.com/Akuli/catris/pull/226). I don't want to go through the same process with Porcupine:

Lol, I didn't know that catris was originally a Python project :))
