### ISSUE TITLE
Switch from editorconfig to toolconfig

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Akuli/porcupine#1404]
This issue is to track the ongoing status of toolconfig, and evaluate if we want to use it over editorconfig.

To be clear, toolconfig is not in a usable state right now, so nothing would be happening soon.

See https://github.com/editorconfig/editorconfig/issues/482 for context, see https://github.com/cxw42/toolconfig-core-py for current status.

**Comment by Akuli** [comment]
What exactly whould the "switching" be? Should Porcupine recognize `.toolconfig` files, maybe with the library you linked as a additional dependency? Should the old editorconfig parsing code be deleted?

So far I haven't seen any projects that come with a toolconfig file, but editorconfig files are becoming popular.

**Comment by benjamin-kirkbride** [comment]
I should give more context instead of assuming everyone would read through everything in the links :)

The creators of editorconfig are working on a successor editorconfig called toolconfig. `toolconfig` is basically a superset of editorconfig, using TOML.

> What exactly would the "switching" be?

(eventually) we replace `.editorconfig` with `.toolconfig.toml

> So far I haven't seen any projects that come with a toolconfig file, but editorconfig files are becoming popular.

toolconfig doesn't exist yet, it's in the design/experimentation stage. I am engaging with them to some extent and figured I would bring it to everyone attention here:
1. to determine if we (Porcupine) is open to using toolconfig over editorconfig
2. so that the Porcupine devs can possibly provide input to help shape the final structure/format of toolconfig

**Comment by Akuli** [comment]
I did look at the links, and saw the tl;dr monologue/proposal and a library that indeed seems very WIP :)

1. Porcupine will support whatever projects use. For example, there's no built-in support for source controls other than Git because nobody seems to be using them. Similarly, I am not interested in supporting toolconfig files until they start to appear in projects that users work on.
2. My input would be that I like the idea of using TOML syntax (editorconfig is pain to parse and the Python library for it is a joke), but I don't like the idea of scrapping/redoing something awesome that is just starting to become popular.

**Comment by benjamin-kirkbride** [comment]
Okay I see my disconnect now.

My "(eventually) we replace .editorconfig with `.toolconfig.toml" comment was aimed towards https://github.com/Akuli/porcupine/blob/main/.editorconfig specifically being replaced, not the EditorConfig plugin or whatever.

> Porcupine will support whatever projects use

I agree we should support EditorConfig for workspaces, as it is somewhat popular and that will likely remain the case.

**Comment by Akuli** [comment]
I'm not interested in replacing Porcupine's `.editorconfig` file with something not supported by Porcupine itself, as I mostly use Porcupine to develop Porcupine. As I already mentioned, I am also not interested in supporting toolconfig in Porcupine yet, because most projects don't use it.

If toolconfig becomes popular in a few years, maybe we can reconsider then, but IMO there's nothing actionable we can/should do now :)

**Comment by benjamin-kirkbride** [comment]
> I'm not interested in replacing Porcupine's .editorconfig file with something not supported by Porcupine itself

A ToolConfig plugin be made before doing that, of course

> I am also not interested in supporting toolconfig in Porcupine yet, because most projects don't use it.

Again, ToolConfig doesn't exist yet, so it's not possible for it to be popular.
