### ISSUE TITLE
Inconsistent ModuleNotFoundErrors

### ISSUE THREAD

**Issue by ethical-haquer** [Akuli/porcupine#1456]
I have two tabs open, both of them Python files.
When I try to run tab one, I get this error:

```
Traceback (most recent call last):
  File "/home/ethical_haquer/fuzzy.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

When I run tab two I _don't_ get any errors.
The funny thing is... both tab one and tab two contain the same import: `import cv2`

This has been bugging me for a while, with multiple different imports and projects, but I've been to lazy to report it. 😊

**Comment by Moosems** [comment]
Very interesting. Maybe the two call different installed versions of Python?

**Comment by rdbende** [comment]
If porcupine finds a python virtual environment, it will automatically activate it before running the script. Is the other file, by chance in a project that has a python venv?

**Comment by Akuli** [comment]
You can control venvs by right-clicking them in the directory tree at left. The currently selected one (if any) shows up with a yellow "venv" in front of it.

You can see which venv Porcupine uses based on the blue command that Porcupine displays when a file runs. With a venv in use, the command is two lines (first line activates venv). Without a venv in use, the command is one line.

**Comment by Akuli** [comment]
Controlling venvs should look like this:

![s](https://github.com/Akuli/porcupine/assets/18505570/341450d7-de7c-4b5d-9e15-81c9c2bddfd3)

I should document all this.

**Comment by Moosems** [comment]
So in a way I was kinda right??

**Comment by ethical-haquer** [comment]
Thanks for all of the replies!
So yeah, the first file uses the `porcupine-venv`, but the second one doesn't.
I'm not sure why they don't both use (or not use) the venv though.
The directory tree doesn't show any venvs - I've only ever used them in Porcupine (that I know of).
Also, what is the proper way to "update" the venv when new modules are installed?
I've tried closing and reopening the app and/or files, but that doesn't work.
TIA.

**Comment by ethical-haquer** [comment]
Another thing, file one is located in my home dir, but file two is in a GitHub repo.

**Comment by Akuli** [comment]
> So yeah, the first file uses the porcupine-venv, but the second one doesn't. I'm not sure why they don't both use (or not use) the venv though.

The porcupine-venv is meant to be used only for Porcupine and its dependencies, not for your projects, so it would make sense to adjust Porcupine's auto-detecting logic so that it never uses a venv that is named `porcupine-venv`.

Currently the auto-detect logic is:

https://github.com/Akuli/porcupine/blob/efcd3b1c9e597a2fb4cdaadd1a51308cd7d829db/porcupine/plugins/python_venv.py#L37

> Also, what is the proper way to "update" the venv when new modules are installed? I've tried closing and reopening the app and/or files, but that doesn't work.

You don't update the venv, you install the dependencies into that venv. This way, if you want to uninstall the things you installed, just delete the whole venv. When you install a dependency into a venv, everything installs into the venv folder. That's the whole point of venvs: you don't pollute your system's Python with all your projects' dependencies.

I recommend making one venv for each project.

To install something into the venv, you activate the venv (with `source name-of-venv/bin/activate`) and then `pip install` as usual.

And again, all of this should be documented, but it isn't...

**Comment by Akuli** [comment]
I started documenting this. For taking screenshots, I temporarily cleared my Porcupine settings. As you might have guessed, Porcupine found my `porcupine-venv` folder and used it as the venv for my `~/hello.py` file.

Please make a pull request that skips folders named `porcupine-venv` in the autodetect logic (or maybe any folders whose name contains `porcupine`).

**Comment by ethical-haquer** [comment]
> I started documenting this. For taking screenshots, I temporarily cleared my Porcupine settings. As you might have guessed, Porcupine found my `porcupine-venv` folder and used it as the venv for my `~/hello.py` file.
> 
> Please make a pull request that skips folders named `porcupine-venv` in the autodetect logic (or maybe any folders whose name contains `porcupine`).

👍 Will do!

**Comment by Akuli** [comment]
This is now documented in `user-doc/projects.md`, but let's keep the issue open until the `porcupine-venv` autodetecting problem is fixed.
