### ISSUE TITLE
no syntax highlighting on windows

### ISSUE THREAD

**Issue by Zaab1t** [Akuli/porcupine#18]

**Comment by Akuli** [comment]
Yes, the syntax highlighter is shit. I used to have a subprocess thing that actually worked on Windows, but multiprocessing is kind of inconsistent as you can see. It wouldn't be hard to convert it back to subprocess, but I'm planning on making a new, much less stupid syntax highlighter anyway. The current version is stupid especially because highlights the whole file every time a single character changes (if it works).

**Comment by Zaab1t** [comment]
I don't have a Windows machine. sorry.

**Comment by Akuli** [comment]
How can you then complain about the highlighting being broken on Windwo$? :D

**Comment by Akuli** [comment]
I have tried a new-ish porcupine on a 32-bit windows 7 running on a real computer, and a 64-bit windows 10 running in a vm. Both worked fine. If the syntax highlighting doesn't work for someone, just comment here and I'll keep working on it.
