### ISSUE TITLE
windows installer

### ISSUE THREAD

**Issue by carlbordum** [Akuli/porcupine#19]
would make it my go-to recommendation for beginners :)

**Comment by Akuli** [comment]
Yes, this and the syntax highlighting. If you can figure out how to create a start menu entry from a setup.py and delete it on `pip uninstall` then I'll be happy to merge a pull request.

**Comment by Akuli** [comment]
I think Porcupine shouldn't be a thing that is installed with pip because I don't want it to be limited to just Python, and people who don't use Python are probably not familiar with pip. I'm feeling like there should be something that lets Windows users run porcupine without installing python first, and ideally without thinking about python at all.

One way to do this would be to distribute porcupine as a standalone executable that Just Works (tm), so that people could just download it and double-click to run. Configuration files would then end up in a user-wide directory as usual. This could be implemented easily with pyinstaller and `--onefile`.

Alternatively, I could create an installer with e.g. Inno Setup, and the installer would install a Python and a Porcupine to `C:\Program Files\Porcupine` or something like that. Using the installer would be a lot like using any other installer, and Inno Setup would take care of creating the start menu entry. If the Porcupine is used for Python, I probably wouldn't want it to run users' programs in the python installed in `C:\Program Files\Porcupine`, so I'd need to check all uses of `sys.executable` in Porcupine, but I'm planning on doing that anyway.

What do you think?

**Comment by Zaab1t** [comment]
An install wizard would be nice. There are many general-purpose editors, so one more tailored for Python is nicer imo. Have you seen https://github.com/takluyver/pynsist?

**Comment by Akuli** [comment]
I haven't seen that one. I'll consider using that if I have any trouble with inno setup. I have used inno setup in the past, and it has worked ok.

**Comment by Akuli** [comment]
well, I should have looked into pynsist earlier... I spent quite a bit of time trying to do exactly what it does, lol.

Anyway, right now I have managed to create a porcupine installer with pynsist, and it actually works. Next I'll fix a few more bugs, write some instructions and merge to master.

**Comment by Akuli** [comment]
Looking very promising so far! :D

![promising](https://user-images.githubusercontent.com/18505570/43683081-66b9a20a-988d-11e8-9bb6-1a1e4d3a7d7c.png)

![promising2](https://user-images.githubusercontent.com/18505570/43683084-6d3d61c0-988d-11e8-975b-ae9d45741eed.png)

**Comment by Akuli** [comment]
it's merged to master now. There are instructions for creating the exes in the README, but I'm not sure how I should distribute the exes yet. I'll probably end up using GitHub's releases page or something, and I'll keep this issue open until the first porcupine release with an exe installer has been done.

**Comment by Zaab1t** [comment]
Thats nice, great work! You could combine that with a github page :)

**Comment by Akuli** [comment]
note to myself: When porcupine is running after installing with this installer, does it show up as `python.exe` or `porcupine.exe` in task manager? What window icon does it have?

**Comment by Akuli** [comment]
needs #29 done first

**Comment by Akuli** [comment]
note to myself: what if you install a porcupine and then later try to install a newer porcupine? Should the setup automagically uninstall the older porcupine first? How do installers of other programs behave if you try to do this?
