### ISSUE TITLE
Buttons to resolve merge conflict have aesthetic issues

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/porcupine#460]
![](https://i.imgur.com/vHbxRvg.png)

**Comment by Akuli** [comment]
It's supposed to look something like this:

![conflict](https://user-images.githubusercontent.com/18505570/120900687-de9c7680-c63e-11eb-961e-52b7e4756dcb.png)

**Comment by ThePhilgrim** [comment]
Looks like this is something similar to a "style.theme_use('default')" issue

**Comment by Akuli** [comment]
Because this is mac-specific, I guess you'll have to fix it yourself. It shouldn't be too difficult though:
1. Write a short program (10 lines or so) that displays one button with custom foreground and background
2. Add another button to the program with different colors
3. Use buttons like that in porcupine/plugins/mergeconflict.py
