### ISSUE TITLE
pluginmanager: treeview not visible

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#573]
The panedwindow collapses in the pluginmanager thus the treeview is not visible in `left_side`. With the `black` theme I can see the sash, but not in light themes.

![image](https://user-images.githubusercontent.com/77941087/124736172-08cfa580-df17-11eb-8de3-cdce5a62b7dd.png)

**Comment by rdbende** [comment]
If I comment out this line:
```python
panedwindow.after(100, lambda: panedwindow.sashpos(0, round(0.7 * DIALOG_WIDTH)))
```
I get this result:
![image](https://user-images.githubusercontent.com/77941087/124737844-a4154a80-df18-11eb-8c69-de4f8adad615.png)

question is whether that line really should be, or maybe the `ttk.Pandewindow` could be replaced with a `tkinter.PanedWindow`, with which we can set a minsize for the panes, and add a `width=10000` to the frames, so that none of them will collapse

**Comment by Akuli** [comment]
The purpose of the commented code is to make both panes visible when the dialog is opened for the first time.

Using `tkinter.Panedwindow` isn't great either, because it can have very different color than the ttk widgets (just replaced `ttk.Panedwindow` with `tkinter.PanedWindow` to try it):

![panedwindow](https://user-images.githubusercontent.com/18505570/124771242-a50fa180-df43-11eb-8da6-457265f8f542.png)

But this is acceptable if it ensures that the treeview will be visible.

**Comment by rdbende** [comment]
However, a `ttk::style lookup` could be used to set the color of the sash to the general fieldbackground

**Comment by Akuli** [comment]
Yes, that is possible. We could borrow the code from `create_passive_text_widget()` in `text_utils.py`.
