### ISSUE TITLE
encoding dropdown

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#705]
would be nice to have a combobox with the available codecs in the popup window instead of the entry

**Comment by Akuli** [comment]
It's awesome that people are trying out the new release :)

Yes, this would be nicer. I initially left it out because I personally would rather type it in, but if you are new to everything and someone told you something about Latin-1 and CRLF and Git, this would let you easily figure out which of those you should enter into the entry. A combobox will let you also type it in if that's what you prefer.
