### ISSUE TITLE
folding: line numbers don't appear when unfolding in small files

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#709]
line numbers don't appear when unfolding in short files

folded:
![image](https://user-images.githubusercontent.com/77941087/130577634-f5878663-9608-4dcc-b4cc-37c455bedaee.png)

unfolded:
![image](https://user-images.githubusercontent.com/77941087/130577736-04a26cd8-696d-4045-a7c9-2e945b2e49fc.png)

the code is there, but the line numbers are not

**Comment by Akuli** [comment]
Currently the line numbers plugin updates when scrolling in the y direction and when the content of the tab changes. Unfolding in a big file results in some scrolling, because the total "length" of the text widget changes.

One way to fix this would be to add a virtual event, let's say `filetab.event_generate("<<UpdateLineNumbers>>")`, to trigger this from the fold plugin.
