### ISSUE TITLE
directory tree mac-specific code

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#751]
Developed without having a Mac user to test all this:
- [ ] Does right-clicking directory tree bring up a menu?
- [ ] Does "Move to trash" work?
- [ ] Does "Open in file manager" work? (directories only)

**Comment by 1anakin20** [comment]
I tested it on macOS Big Sur and, 
- [ ] Does right-clicking directory tree bring up a menu?
No it doesn't. However, as it is commented, it works when the button is set to 2 instead of 3.

The following where tested by changing the button to 2:
- [x] Does "Move to trash" work?
- [x] Does "Open in file manager" work? (directories only)

I'm thinking of adding an if statement to set the button to 2 if the OS is macOS. Or do you have another idea?

**Comment by Akuli** [comment]
An if statement would work, but creating a virtual event defined in `default_keybindings.toml` would be better. Run `git grep "<<TabClosing:ShowMenu>>"` to find an example of how to do this. The tcl code looks a bit weird, but `if {[tk windowingsystem] == "aqua"} {` checks whether it is running on MacOS.

The virtual event could be named `<<RightClick>>` or something, so that all other right-clicking can use the same virtual event instead of having to copy/paste the `if` statement everywhere.
