### ISSUE TITLE
README Edit

### ISSUE THREAD

**Issue by Mannuel25** [Akuli/porcupine#821]
I'd like to make a few changes to the README; move the Developing Porcupine section into a new file called **Contributing Guidelines**, add a few Git/GitHub resources for people that wish to contribute but aren't familiar with using Git/GitHub. 

I also suggest we have a [Code Of Conduct](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project), we could make use of [Contributor Covenant](https://www.contributor-covenant.org/). 

If I'm granted the go-ahead, I will make the stated changes to the repository.

**Comment by Akuli** [comment]
Please fork the repo, edit the README in your fork like you imagined it to be, and make a pull request. We can then talk about what edits I actually want to have in the README.

Instead of linking Git and GitHub resources, it might be better to recommend contacting me if someone doesn't know how to use Git and GitHub. It's ok to ask for help, and in my experience people new to git need someone else to fix their messes several times during the learning process.

**Comment by Mannuel25** [comment]
Okay, I'll do just that. Thanks.

**Comment by Mannuel25** [comment]
I forgot to add that the editor is really cool!. I love it :sunglasses:
